import React from 'react';

const PrivacyPolicy = () => {
    return (
        <div className="container mx-auto px-4 py-10">





            <div class="cart-head border-b h-[120px] sm:h-[220px] flex items-center text-center justify-center relative">
                <div class="flex relative cart-h-text custom-container flex-col h-auto w-full text-center justify-center">
                    <p class="text-[20px]  sm:text-[26px] lg:text-[30px] font-bold"> Privacy & Policy</p>
                    <a href="#" class="text-center   text-[12px] cart-access lg:text-[14px]">
                        <span class=" ">Home /</span> Privacy & Policy
                    </a>
                </div>
                <div class="overlay2"></div>
            </div>





            <section class="custom-container lg:px-[230px] md:px-[150px] sm:px-10 privacy-head-div text-[16px] mb-20">


                <span class=" ">Last updated: March 09, 2023</span>
                <p class="mt-6 text-justify">
                    This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
                    information when You use the Service and tells You about Your privacy rights and how the law protects You.
                </p>
                <p class="mt-6 text-justify">
                    We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
                    collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been
                    created with the help of the TermsFeed Privacy Policy Generator.
                </p>

                <h2 class="my-6 head-tearms">Interpretation</h2>
                <p class="text-justify">
                    The words of which the initial letter is capitalized have meanings defined under the following conditions.
                    The following definitions shall have the same meaning regardless of whether they appear in singular or in
                    plural.
                </p>




                <h2 class="my-6 head-tearms">Definitions</h2>
                <p>
                    For the purposes of this Privacy Policy:
                </p>
                <div class="ul mt-4">

                    <li><strong>Account:</strong> A unique account created for You to access our Service or parts of our
                        Service.</li>
                    <li><strong>Affiliate:</strong> An entity that controls, is controlled by or is under common control with a
                        party, where "control" means ownership of 50% or more of the shares, equity interest or other securities
                        entitled to vote for election of directors or other managing authority.</li>
                    <li><strong>Company:</strong> Blueskytech, 268 St, South New York/NY 98944, United States.</li>
                    <li><strong>Cookies:</strong> Small files that are placed on Your computer, mobile device or any other
                        device by a website, containing the details of Your browsing history on that website among its many
                        uses.</li>
                    <li><strong>Country:</strong> New York, United States.</li>
                    <li><strong>Device:</strong> Any device that can access the Service such as a computer, a cellphone or a
                        digital tablet.</li>
                    <li><strong>Personal Data:</strong> Any information that relates to an identified or identifiable
                        individual.</li>
                    <li><strong>Service:</strong> The Website.</li>
                    <li><strong>Service Provider:</strong> Any natural or legal person who processes the data on behalf of the
                        Company. It refers to third-party companies or individuals employed by the Company to facilitate the
                        Service, to provide the Service on behalf of the Company, to perform services related to the Service or
                        to assist the Company in analyzing how the Service is used.</li>
                    <li><strong>Third-party Social Media Service:</strong> Any website or any social network website through
                        which a User can log in or create an account to use the Service.</li>
                    <li><strong>Usage Data:</strong> Data collected automatically, either generated by the use of the Service or
                        from the Service infrastructure itself (for example, the duration of a page visit).</li>
                    <li><strong>Website:</strong> Prime, accessible from <a
                        href="https://blueskytechmage.com/gota/">https://blueskytechmage.com/gota/</a></li>
                    <li><strong>You:</strong> The individual accessing or using the Service, or the company, or other legal
                        entity on behalf of which such individual is accessing or using the Service, as applicable.</li>

                </div>


                <h2 class="my-6 head-tearms">Personal Data</h2>
                <p class="text-justify">
                    While using Our Service, We may ask You to provide Us with certain personally identifiable information that
                    can be used to contact or identify You. Personally identifiable information may include, but is not limited
                    to:
                </p>
                <div class="ul">
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Address, State, Province, ZIP/Postal code, City</li>
                    <li>Usage Data</li>
                </div>
                <h2 class="my-6 head-tearms">Usage Data</h2>
                <p>
                    Usage Data is collected automatically when using the Service.
                </p>
                <p class="text-justify">
                    Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address),
                    browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the
                    time spent on those pages, unique device identifiers and other diagnostic data.
                </p>
                <p class="text-justify">
                    When You access the Service by or through a mobile device, We may collect certain information automatically,
                    including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP
                    address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use,
                    unique device identifiers and other diagnostic data.
                </p>
                <p class="text-justify">
                    We may also collect information that Your browser sends whenever You visit our Service or when You access
                    the Service by or through a mobile device.
                </p>









                <h2 class="my-6 head-tearms">Tracking Technologies and Cookies</h2>

                <p class="text-justify">We use Cookies and similar tracking technologies to track the activity on Our Service
                    and store certain
                    information. Tracking technologies used are beacons, tags, and scripts to collect and track information and
                    to improve and analyze Our Service. The technologies We use may include:</p>


                <div class="ul mt-4">

                    <li><strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on Your Device. You can
                        instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You
                        do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted
                        Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                    <li><strong>Web Beacons:</strong> Certain sections of our Service and our emails may contain small
                        electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel
                        gifs) that permit the Company, for example, to count users who have visited those pages or opened an
                        email and for other related website statistics (for example, recording the popularity of a certain
                        section and verifying system and server integrity).</li>


                </div>
                <p class="my-4 text-justify">
                    Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or
                    mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
                    You can learn more about cookies on TermsFeed website article.
                </p>
                <p>
                    We use both Session and Persistent Cookies for the purposes set out below:


                </p>


                <div class="ul mt-4">

                    <li>
                        <strong>Necessary / Essential Cookies</strong>
                        <ul>
                            <li><strong>Type:</strong> Session Cookies</li>
                            <li><strong>Administered by:</strong> Us</li>
                            <li><strong>Purpose:</strong> These Cookies are essential to provide You with services available
                                through the Website and to enable You to use some of its features. They help to authenticate
                                users and prevent fraudulent use of user accounts. Without these Cookies, the services that You
                                have asked for cannot be provided, and We only use these Cookies to provide You with those
                                services.</li>
                        </ul>
                    </li>
                    <li>
                        <strong>Cookies Policy / Notice Acceptance Cookies</strong>
                        <ul>
                            <li><strong>Type:</strong> Persistent Cookies</li>
                            <li><strong>Administered by:</strong> Us</li>
                            <li><strong>Purpose:</strong> These Cookies identify if users have accepted the use of cookies on
                                the Website.</li>
                        </ul>
                    </li>
                    <li>
                        <strong>Functionality Cookies</strong>
                        <ul>
                            <li><strong>Type:</strong> Persistent Cookies</li>
                            <li><strong>Administered by:</strong> Us</li>
                            <li><strong>Purpose:</strong> These Cookies allow us to remember choices You make when You use the
                                Website, such as remembering your login details or language preference. The purpose of these
                                Cookies is to provide You with a more personal experience and to avoid You having to re-enter
                                your preferences every time You use the Website.</li>
                        </ul>
                    </li>


                </div>

                <p class="my-4 text-justify">
                    For more information about the cookies we use and your choices regarding cookies, please visit our Cookies
                    Policy or the Cookies section of our Privacy Policy.


                </p>



                <h2 class="my-6 head-tearms">Use of Your Personal Data</h2>
                <p class="text-justify  ">
                    <div class="ul">

                        <li><strong>To provide and maintain our Service:</strong> Including to monitor the usage of our Service.
                        </li>
                        <li><strong>To manage Your Account:</strong> To manage Your registration as a user of the Service. The
                            Personal Data You provide can give You access to different functionalities of the Service that are
                            available to You as a registered user.</li>
                        <li><strong>For the performance of a contract:</strong> The development, compliance and undertaking of the
                            purchase contract for the products, items or services You have purchased or of any other contract with
                            Us through the Service.</li>
                        <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent
                            forms of electronic communication, such as a mobile application's push notifications regarding updates
                            or informative communications related to the functionalities, products or contracted services, including
                            the security updates, when necessary or reasonable for their implementation.</li>
                        <li><strong>To provide You with news, special offers and general information:</strong> About other goods,
                            services and events which we offer that are similar to those that you have already purchased or enquired
                            about unless You have opted not to receive such information.</li>
                        <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
                        <li><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger,
                            divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our
                            assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in
                            which Personal Data held by Us about our Service users is among the assets transferred.</li>
                        <li><strong>For other purposes:</strong> We may use Your information for other purposes, such as data
                            analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to
                            evaluate and improve our Service, products, services, marketing and your experience.</li>



                        <li><strong>We may share Your personal information in the following situations:</strong></li>

                        <li><strong>With Service Providers:</strong> We may share Your personal information with Service
                            Providers to monitor and analyze the use of our Service, to contact You.</li>
                        <li><strong>For business transfers:</strong> We may share or transfer Your personal information in
                            connection with, or during negotiations of, any merger, sale of Company assets, financing, or
                            acquisition of all or a portion of Our business to another company.</li>
                        <li><strong>With Affiliates:</strong> We may share Your information with Our affiliates, in which case
                            we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company
                            and any other subsidiaries, joint venture partners or other companies that We control or that are
                            under common control with Us.</li>
                        <li><strong>With business partners:</strong> We may share Your information with Our business partners to
                            offer You certain products, services or promotions.</li>
                        <li><strong>With other users:</strong> When You share personal information or otherwise interact in the
                            public areas with other users, such information may be viewed by all users and may be publicly
                            distributed outside. If You interact with other users or register through a Third-Party Social Media
                            Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures
                            and description of Your activity. Similarly, other users will be able to view descriptions of Your
                            activity, communicate with You and view Your profile.</li>
                        <li><strong>With Your consent:</strong> We may disclose Your personal information for any other purpose
                            with Your consent.</li>


                    </div>
                </p>





                <h2 class="my-6 head-tearms">Cookies</h2>
                <p class="text-justify">
                    We use data collection devices such as "cookies" on certain pages of the Platform to help analyze our web
                    page flow, measure promotional effectiveness, and promote trust and safety. "Cookies" are small files placed
                    on your hard drive that assist us in providing our services. Cookies do not contain any of your personal
                    information. We offer certain features that are only available through the use of a "cookie". We also use
                    cookies to allow you to enter your password less frequently during a session. Cookies can also help us
                    provide information that is targeted to your interests. Most cookies are "session cookies," meaning that
                    they are automatically deleted from your hard drive at the end of a session. You are always free to
                    decline/delete our cookies if your browser permits, although in that case you may not be able to use certain
                    features on the Platform and you may be required to re-enter your password more frequently during a session.
                    Additionally, you may encounter "cookies" or other similar devices on certain pages of the Platform that are
                    placed by third parties. We do not control the use of cookies by third parties. We use cookies from
                    third-party partners such as Google Analytics for marketing and analytical purposes. Google Analytics help
                    us understand how our customers use the site. You can read more about how Google uses your personal
                    information here: https://www.google.com/intl/en/policies/privacy/. You can opt-out of Google Analytics
                    here: https://tools.google.com/dlpage/gaoptout. You can also control the use of cookies at the individual
                    browser level, but if you choose to disable cookies, it may limit your use of certain features or functions
                    on the services.

                </p>


                <h2 class="my-6 head-tearms">Retention of Your Personal Data</h2>
                <p class="text-justify">
                    The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this
                    Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal
                    obligations (for example, if we are required to retain your data to comply with applicable laws), resolve
                    disputes, and enforce our legal agreements and policies.

                    The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for
                    a shorter period of time, except when this data is used to strengthen the security or to improve the
                    functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
                </p>
                <h2 class="my-6 head-tearms">Transfer of Your Personal Data</h2>
                <p class="text-justify">
                    Your information, including Personal Data, is processed at the Company's operating offices and in any other
                    places where the parties involved in the processing are located. It means that this information may be
                    transferred to — and maintained on — computers located outside of Your state, province, country or other
                    governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.

                    Your consent to this Privacy Policy followed by Your submission of such information represents Your
                    agreement to that transfer.

                    The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in
                    accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization
                    or a country unless there are adequate controls in place including the security of Your data and other
                    personal information.
                </p>
                <h2 class="my-6 head-tearms">Delete Your Personal Data</h2>
                <p class="text-justify">
                    By visiting our Platform or by providing your information, you consent to the collection, use, storage,
                    disclosure and otherwise processing of your information (including sensitive personal information) on the
                    Platform in accordance with this Privacy Policy. If you disclose to us any personal information relating to
                    other people, you represent that you have the authority to do so and to permit us to use the information in
                    accordance with this Privacy Policy.
                </p>





                <h2 class="my-6 head-tearms">Business Transactions</h2>
                <p class="text-justify">
                    If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We
                    will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy
                    Policy.
                </p>
                <h2 class="my-6 head-tearms">Law enforcement</h2>
                <p class="text-justify">
                    Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so
                    by law or in response to valid requests by public authorities (e.g. a court or a government agency).
                </p>








                <h2 class="my-6 head-tearms">Other legal requirements</h2>
                <p class="text-justify">
                    The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
                </p>
                <div class="ul    text-justify">
                    < li > Comply with a legal obligation</li >
                    <li>Protect and defend the rights or property of the Company</li>
                    <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                    <li>Protect the personal safety of Users of the Service or the public</li>
                    <li>Protect against legal liability</li>
                </div >



                <h2 class="my-6 head-tearms">Security of Your Personal Data</h2>
                <p class="text-justify">
                    The security of Your Personal Data is important to Us, but remember that no method of transmission over the
                    Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable
                    means to protect Your Personal Data, We cannot guarantee its absolute security.
                </p>
                <h2 class="my-6 head-tearms">Children's Privacy</h2>
                <p class="text-justify">
                    Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable
                    information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your
                    child has provided Us with Personal Data, please contact Us. If We become aware that We have collected
                    Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to
                    remove that information from Our servers.

                    If We need to rely on consent as a legal basis for processing Your information and Your country requires
                    consent from a parent, We may require Your parent's consent before We collect and use that information.
                </p>
                <h2 class="my-6 head-tearms">Links to Other Websites</h2>
                <p class="text-justify">
                    Our Service may contain links to other websites that are not operated by Us. If You click on a third party
                    link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy
                    of every site You visit.

                    We have no control over and assume no responsibility for the content, privacy policies or practices of any
                    third party sites or services.
                </p>
                <h2 class="my-6 head-tearms">Changes to this Privacy Policy</h2>
                <p class="text-justify">
                    We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new
                    Privacy Policy on this page.

                    We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming
                    effective and update the "Last updated" date at the top of this Privacy Policy.

                    You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy
                    are effective when they are posted on this page.
                </p>
                <h2 class="my-6 head-tearms">Contact Us</h2>
                <p class="text-justify">
                    If you have any questions about this Privacy Policy, You can contact us:

                    <li>
                        By email: demo.Prime@gmail.com
                    </li>
                </p>

            </section >











        </div >
    );
}

export default PrivacyPolicy;
